apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
  namespace: prometheus
spec:
  secretName: prometheus-tls
  dnsNames:
  - "prometheus"
  - "*.prometheus.svc.cluster.local"
  - "*.prometheus"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer