apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: agnhost
  namespace: agnhost
spec:
  secretName: agnhost-tls
  dnsNames:
  - "agnhost"
  - "*.agnhost.svc.cluster.local"
  - "*.agnhost"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer