apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: grafana
spec:
  secretName: grafana-tls
  dnsNames:
  - "grafana"
  - "*.grafana.svc.cluster.local"
  - "*.grafana"
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer